### PR TITLE
Added support LineageOS 14.1 & Stock Oreo for Galaxy s7 & edge

### PR DESCRIPTION
**Pull request by Svirusx**
I think code versions are fine for pull but if you want you can they change
Stock Oreo = herolte-o & hero2lte-o
LineageOS 14.1 = herolte-cm & hero2lte-cm

### CODE REVIEW

**Comment by kimocoder** [comment]
@Svirusx what does this kernel got of support? does it have HID support? wireless extension (modules) ? injection support for wifi? has it been properly tested?

**Comment by Svirusx** [comment]
BadUSB
HID gadget keyboard/mouse
DriveDroid
USB WiFi, mac80211(Monitor mode, packet capture, packet injection)
F2FS
Bluetooth HCI USB support
RTL-SDR DVB support

No modules in LineageOS 14.1 i included all in kernel. It is small.
In Stock Oreo all from those list works too but i'm going to add modules in future releases to get some extra features like NFS v4 or CIFS

**Comment by Re4son** [comment]
Awesome, thanks.
Is there a way to integrate your "herolte-o" and "hero2lte-o" sections into the existing "herolte" and "hero2lte" respectively? The correct kernel version is chosen with the "--oreo" command line argument. You can use the "flounder" section as an example.

**Comment by Svirusx** [comment]
Cleared my repo and merged my versions with marshmallow one.

**Comment by Re4son** [comment]
Almost there, just one more question: the devices.cfg lists the following new devices:

herolte
herolte-cm
hero2lte-cm

But the kernel images are placed in these directories:

herolte
hero2lte

Could you help us with getting them aligned please?
Many thanks.

**Comment by Svirusx** [comment]
Aligned Nougat LineageOS v14.1 versions.

**Pull request merged**
