### PR TITLE
add support for oneplus6

### PR DESCRIPTION
**Pull request by cm-punk**
`# OnePlus6
[oneplus6-oos]
author = "cmpunk"
version = "1.0"
arch = arm64
devicenames = OnePlus6 
`

### CODE REVIEW

**Comment by darksty** [comment]
yes

**Comment by liudaozhenjun** [comment]
+1

**Comment by Re4son** [comment]
Sounds exciting but this pull request seems to contain the wrong commit (OnePlus6 != Galaxy S8/S8+/Note8).

Would you mind adjusting that?

**Comment by Re4son** [comment]
Closed due to inactivity.
Please re-open with the required adjustments if still needed.

**Pull request closed without merging**
