### PR TITLE
Nexus 5X (bullhead) NetHunter Kernel Android 8.1 April Update

### PR DESCRIPTION
**Pull request by bencejuhaasz**
source: https://github.com/bencejuhaasz/bullhead 
Features: 
- packet injection (Ralink, Realtek, Atheros...) 
- Bluetooth USB 
- RTL-SDR via userspace apps (kernel support for SDR's removed because  it crashed already  working userspace drivers, but any of them can be  added if you don't use the userspace ones) 
- /proc/config.gz support 
- loadable module support
- system v ipc (for systemd) 
- elementalx features -> stable, doesn't use too much power 
WIP: 
- USB HID Keyboard emulation

### CODE REVIEW

**Comment by rafaleon69** [comment]
Any chance you can also add support for Nexus 6P Oreo 8.1, the Oreo 8.0 kernel I tried does not boot the rom ? I will really appreciate your effort!

All the best.

**Comment by bencejuhaasz** [comment]
For the 6P I can try to add the NetHunter features to the defconfig and try to build it, but i don't have a device to test it. Most of the porting work for the 5X was just applying the commints and carefully choosing the features in the defconfig, some of them stop the build with error.

**Comment by rafaleon69** [comment]
I will be more than happy to test it for you once you build it. I will be waiting for your reply!

**Comment by rafaleon69** [comment]
If you can build it with at least HID support I, or others will definitely appreciate it!

**Comment by bencejuhaasz** [comment]
Tomorrow I'm going to try to build it.

**Comment by rafaleon69** [comment]
Thanks a lot! I will watch this space.

Good luck.

**Comment by rafaleon69** [comment]
I see, is it the same issue with the stock 8.1 kernel from google ?

**Comment by rafaleon69** [comment]
All right , thank you for trying.

**Comment by JamesNKing** [comment]
I am pretty new to the whole installing unofficially supported roms, and i'm just looking for some help. I currently own a Nexus 5X (bullhead) running android Oreo 8.1.0. This is my only operating cell phone that I can use, but I would like to be able to use it for my pen testing. If you will, I need some help installing this properly without bricking my device.

**Comment by bencejuhaasz** [comment]
If you read the descriptions carefully you probably won't break it. The nethunter is currently not fully supported on bullhead and 8.1.0. The nethunter app and it's scripts aren't working, the usb hid emulation is not implemented yet on oreo. The pentesting features you can use at the time on your phone is a chroot, support for usb wifi cards, rtl-sdr support (it's a factory feature, you don't need mods for it, just 2 apk's from google play) and maybe usb bluetooth. These features are hard to manage on nethunter. For example you can have only one chroot. I recommend using lineage (you can choose AOSP too) and my custom kernel https://github.com/bencejuhaasz/bullhead , and the Linux Deploy app. You can get all the available features on your phone with them in a more convenient way.
A short todo list to get the above working:
1 Decide if you'd like to use (A) official, large and too battery draining google apps, or (B) smaller, unofficial, but more convenient, custom google apps.
2 In case A install lineage with opengapps or a google factory image. In case B install lineage with microg, they have a separate website with a zip installer, just like the official lineage. Both methods have detailed descriptions already. For Lineage you need a custom recovery, I recommend twrp.
3 Root it. Lineage has an own method.
4 Install linux deploy and configure it.
5 Install my custom kernel. You can build it from the source, or I can give an installer if you are interested.

**Comment by LizardHarry** [comment]
Which wifi card chipsets are supported? Is there a list of supported (e. g. Realtek) chipsets?

**Comment by melissa200** [comment]
> 5 Install my custom kernel. You can build it from the source, or I can give an installer if you are interested.

@bencejuhaasz I would be interested in grabbing that installer, if that's still possible? I don't have access to a build environment at the moment  :)

**Comment by bencejuhaasz** [comment]
>  I would be interested in grabbing that installer, if that's still possible? I don't have access to a build environment at the moment :)
It's still possible, but that kernel was compiled in August (has August security patch) and is based on ElementalX. Since then I've found the sphinx kernel, which is better at battery saving, because it can turn off cores. I can compile a sphinx-based kernel with all the above mentioned features except module support today or tomorrow. Please understand that I don't want to upload a kernel with old security patches and bad power management. I'd be thankful if you could help solving the module loading support, the kernel just doesn't boot if that's enabled.

**Comment by bencejuhaasz** [comment]
I've built the installer, but it bootloops at the google logo.

**Comment by Re4son** [comment]
Closed due to inactivity.
Please re-open with the missing information if required.

**Pull request closed without merging**
