### PR TITLE
[Upgrade] Galaxy S6 Kernel

### PR DESCRIPTION
**Pull request by XXH3X**
This is a upgrade from my older kernel source pointed in this [pull](https://github.com/offensive-security/nethunter-devices/pull/162), everything is working but HiD. I can make HiD work with the synapse support on the ramdisk. I only need to know if I should add the synapse support for HiD or not

### CODE REVIEW

**Comment by Re4son** [comment]
Would be great if you could. Any downsides to this?

**Comment by XXH3X** [comment]
@Re4son, nope any. I just didn't added it because it's a different app and support apart from the nethunter project. In that case I'm just finishing some tests and I'll add it right away

**Comment by XXH3X** [comment]
@Re4son Just finished everything, I think it is ready for merge, everything works, it has wireguard support and I added support for alot of wifi cards

**Comment by Re4son** [comment]
Awesome job, thanks.

**Comment by XXH3X** [comment]
Thanks :)

**Pull request merged**
