### PR TITLE
Add hammerheadmon-nougat

### PR DESCRIPTION
**Pull request by AutinDroid**
This is Chrisk44's kernel patched for Nexmon in chroot. Source can be found here: https://github.com/AutinDroid/HammerheadMon-Kernel/tree/Nexmon-Patches
This kernel is for AOSP based nougat ROMs on the Nexus 5.

### CODE REVIEW

**Comment by AutinDroid** [comment]
Nobody?

**Comment by jcadduono** [comment]
err theres a space after the version string in devices.cfg, fix that i guess and it should be good to go

@binkybear

**Comment by AutinDroid** [comment]
Ok fixed.

**Comment by nethunteros** [comment]
Kernel should be fine.  We discussed issues here: https://github.com/seemoo-lab/bcm-public/issues/5

It just needs modified firmware for vendor, chroot ioctl intercept, and a custom start/stop script which would be done outside of kernel.

**Comment by AutinDroid** [comment]
I believe that the tools, intercept, and start/stop script can be placed in the kernel installer, having all the things installed to /system/xbin. Firmware can be installed via Nexmon app.

**Comment by nethunteros** [comment]
The way the kernel installer is setup now is a bit more generic so you would have to make a more custom version but that should be easy (then include nexmon app).

**Comment by jcadduono** [comment]
you can technically include anything in the ramdisk folder of a kernel then use patch.d script to move/install those items from ramdisk to elsewhere.

**Pull request merged**
