### PR TITLE
Add One M7 GPE

### PR DESCRIPTION
**Pull request by lavanoid**
Add support for the HTC One M7. Been using this for several months now and everything works.

### CODE REVIEW

**Comment by jcadduono** [comment]
you should use ueventd to set device node permissions!

i can add a function to the installer so you can use a patch.d script for modifying ueventd (this is a good job for awk)

hidg0 and hidg1 are normally created as 600 root:root, which should actually work fine - hidg accessing apps should already be running as root, so what is the real issue here?

**Comment by lavanoid** [comment]
I wasn't aware of using ueventd (my knowledge isn't THAT extensive).

I don't know why but on my M7, the keyboard gadget refuses to work until I manually set the permissions to 666 (as documented by in the readme.md of the keyboard gadget patch). That's why I added the init script to do that. Without it, the USB keyboard app freezes when using the keyboard and the duckhunter feature of the NH app, refuses to work at all.

I temporarily disabled SELinux due to Authorizer not working (it will be re-enabled once Authorizer adds superuser support).

**Comment by jcadduono** [comment]
selinux is normally in permissive mode on nethunter kernels to allow for chroot to function anyway, is usb keyboard app not asking for superuser? it's rather dangerous to use 666 on a device node with selinux permissive, as it would grant every app the ability to to use it without needing to grant it any access.

**Comment by lavanoid** [comment]
The keyboard app asks for superuser permissions and it allows only mouse interaction. Literally as soon as I try using keyboard input, the app locks up. In Duckhunter, I click "Launch attack" but it does nothing.

If you'd like, I could make a video (maybe at the weekend) that documents exactly what happens before and after changing the permissions to 666/disabling selinux.

**Comment by lavanoid** [comment]
Weird. Seems to have fixed itself. I removed the startup script that changes permissions and it works with the USB Keyboard app and the Duckhunter. A few days ago, keyboard emulation refused to work at all. I'll remove my "fixes".

**Comment by jcadduono** [comment]
here's some voodoo magic that may also help, just committed (you shouldn't need to set it yourself, since i added it to init.nethunter.rc for all devices):

https://github.com/offensive-security/kali-nethunter/commit/503ea203f089ec4a7fa924585241415fa12ef8ba

**Comment by lavanoid** [comment]
Awesome. I assume everything is fine to be merged now?

**Comment by jcadduono** [comment]
Would you be able to separate your kernel sources into a different repo and update the sources link? (kernel sources should be at top level dir)
preferably under a name such as: `android_kernel_htc_m7gpe` with branch named as the android revision, ex. `android-5.1` or `nethunter-5.1`

you have a dangerous recursive loop in your kernel sources, you should remove that immediately:
https://github.com/lavanoid/M7GPE_Kali/blob/master/kernel/drivers/usb/gadget/android.c#L2292
(including the printk above it, it is not necessary)
this should be enough:
https://github.com/lavanoid/M7GPE_Kali/blob/master/kernel/drivers/usb/gadget/android.c#L2404
(although it should really be this):
```c
name = "hid";
err = android_enable_function(dev, name);
if (err)
    pr_err("android_usb: Cannot enable '%s'", name);
```

the line directly below it,
```c
htc_usb_enable_function("hid", 1);
```
appears to be in the wrong area, and should probably be located here:
https://github.com/lavanoid/M7GPE_Kali/blob/master/kernel/drivers/usb/gadget/android.c#L401

(yikes htc why would you go and make another node like that?!?!)

**Comment by lavanoid** [comment]
Will do, I'll make the changes tomorrow or at the weekend (college life) :)

Gotta love HTC for messing up the gadget driver, I know. I had to apply some patches on top of the ones Blinkybear provided, which are described here: https://github.com/lavanoid/M7GPE_Kali/commit/77e536259952cc1d51a24fe09a9c0a647fc2670c#commitcomment-19559306

I'll make your changes and test ASAP.

**Comment by lavanoid** [comment]
Fixes applied: https://github.com/lavanoid/android_kernel_htc_m7gpe/commit/e653f012c7ce45feeecb02b4b26a6278ff7d4d05

**Comment by jcadduono** [comment]
bad indentation at https://github.com/lavanoid/android_kernel_htc_m7gpe/commit/e653f012c7ce45feeecb02b4b26a6278ff7d4d05#diff-20e772caf2d08dbdcc1e6822e531717eR401 :$ least it wont affect output

**Comment by lavanoid** [comment]
The indentation seems fine to me o.o

**Comment by jcadduono** [comment]
i don't know how you can't see it, but you have the hid enable indented to where you might expect it to be part of the acm if statement (it should not be)

**Comment by lavanoid** [comment]
Oh, I thought it HAD to be on the same indentation level as it.

**Comment by lavanoid** [comment]
All fixed.

**Comment by jcadduono** [comment]
Alright, if it's all working/tested, can you please rebase it into 1 commit (git rebase -i HEAD~X) (pick -> fix for extra commits)

**Comment by lavanoid** [comment]
UUh, isn't it possible to merge my added commits directly? I can try to rebase it but I'd likely mess something up.

**Comment by jcadduono** [comment]
it's very easy to just git rebase -i HEAD~3 and change your picks on Update kernels.txt and Fixed HID Gadget to fix, then git push -f

if all you do is change p to f you will squash but there will be no differences at all :)

**Comment by lavanoid** [comment]
Done :D

**Comment by jcadduono** [comment]
welcome to device maintenance life ;)

**Comment by lavanoid** [comment]
Awesome :D Now for the appearance on the Wiki table.

**Comment by jcadduono** [comment]
done.

**Pull request merged**
