### PR TITLE
Added S6 AOSP Files

### PR DESCRIPTION
**Pull request by madScript01**
Just build a kernel for the Galaxy S6/S6 Edge to support the Kali Nethunter and hopefully it will join the repo, I added the files that were build after I finished make the Images. I already tested them and I'm using it in AOSP Android Nougat

### CODE REVIEW

**Comment by jcadduono** [comment]
As S6 is one of the devices with a small boot partition which does not support compressed kernel images, and your resulting one is only 20 MB, yet you lack modules, I think you're missing a few of the nethunter related driver modules, If you need to save space, do consider enabling module support and building a few things as modules. (you might need to remote TIMA auto-enabling from a kconfig to allow modules to be supported)

The files you need are Image and dtb.img, here is a script I wrote to compile dtb.img from kernel sources:
https://github.com/jcadduono/android_kernel_samsung_universal7420/blob/android-6.0/dtbgen.sh
You will also need exynos dtbTool from https://github.com/jcadduono/android_kernel_samsung_universal7420/tree/android-6.0/scripts/dtbTool

**Comment by madScript01** [comment]
I think I didn't miss any drivers, because I got monitor modelo working and I could use the TP-Link w722n WiFi adapter. But Im going to see what I can do. Thanks for the reply

**Comment by jcadduono** [comment]
also need to edit kernels.txt very important to have source available publicly

**Comment by madScript01** [comment]
Ok, thanks I wiil do what I can. Thanks for the reply

**Comment by madScript01** [comment]
I'm going to do some more research in adding some functions. Later I'll open another pull request

**Pull request closed without merging**
