### PR TITLE
[Oneplus3cm] Add kernel for Cyanogenmod

### PR DESCRIPTION
**Pull request by ttimasdf**

### CODE REVIEW

**Comment by jcadduono** [comment]
please use:
```sh
git remote add ofsc https://github.com/offensive-security/nethunter-devices.git
git fetch ofsc experimental
git checkout ofsc/experimental
git cherry-pick c7a6acf87443bc1e9a67a2695a58fb2266a94e49
```
then make sure your cherry-picked commit (of your changes) applies cleanly over the current git HEAD of that branch (what we got from doing above commands)

then you can force push (git push -f) to your branch to update it, and this pull request, so it isn't all broken and changing tons of files.

**Comment by ttimasdf** [comment]
Oh, sorry for messing up the PR, I have little experience with git, messed up my local repo as well (lots of merge conflicts). I will fix it asap.

btw, I tested my kernel and it worked well, only I noticed when the kernel size larger than a specific point, the phone will hang at boot, so I have to modulize some of the drivers and do modprobe after boot. Is there any suggestion? If this is solved, then maybe I could push it into the master branch.

**Comment by jcadduono** [comment]
I had near the same issue and had to use modules on gracelte/herolte/hero2lte (boot image because too big for partition due to large kernel Image) - you can see how I went about it here:

https://github.com/offensive-security/nethunter-devices/commit/7e9497a71d099b1ad7598fe157b176eed13dcc53  
https://github.com/jcadduono/android_kernel_samsung_universal8890/blob/nethunter-6.0/build.sh#L112
https://github.com/offensive-security/kali-nethunter/commit/76a29e502ab5b621da88fb5ffdd3aa0161ec4221

so at least modprobe should be able to catch them now with just module names and not paths from the chroot
i guess consider using the same layout in nethunter devices that i'm using for shieldtablet/herolte/gracelte

if you want the modules to load on boot, you can add your own init.rc to ramdisk folder in your device folder like:
init.nethunter-onyx.rc:
```
on boot
    insmod /system/lib/modules/3.4.x-yourkernel/path/to/module1.ko
    insmod /system/lib/modules/3.4.x-yourkernel/path/to/module2.ko
```
you'll probably have to go by depmod order i'm not sure how smart init's insmod is
then make a patch.d file like so:
06-nethunter-onyx-rc
```sh
#!/sbin/sh

. "$env"

print "Importing init.nethunter-onyx.rc to init.rc"
insert_after_last init.rc "import /init\\..*\\.rc" "import /init.nethunter-onyx.rc"

exit 0
```

you could also avoid creating a separate init rc file by doing this:
(it should be safe from duplications since init.nethunter.rc is created anew each time you flash kernel)
```sh
#!/sbin/sh

. "$env"

print "Adding module loading to init.nethunter.rc"
cat << EOF >> init.nethunter.rc

on boot
    insmod /system/lib/modules/3.4.x-yourkernel/path/to/module1.ko
    insmod /system/lib/modules/3.4.x-yourkernel/path/to/module2.ko
EOF

exit 0
```

**Comment by ttimasdf** [comment]
I've compiled the kernel several time with different settings. without luck. SELinux blocked init from loading modules at boot.

```
root@oneplus3:/ # dmesg|grep audit
[    1.481404]@3 SELinux:  Permission audit_read in class capability2 not defined in policy.
[    1.506345]@3 audit: type=1403 audit(8087818.553:2): policy loaded auid=4294967295 ses=4294967295
[    1.506645]@3 audit: type=1404 audit(8087818.553:3): enforcing=1 old_enforcing=0 auid=4294967295 ses=4294967295
[    2.081992]@0 logd.auditd: start
[   13.727069]@0 type=1400 audit(8087830.776:4): avc: denied { read } for pid=444 comm="busybox_nh" name="userinit.d" dev="sda15" ino=1831430 scontext=u:r:sysinit:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=0
[   14.002910]@0 type=1400 audit(8087831.026:5): avc: denied { execute_no_trans } for pid=472 comm="init" path="/system/xbin/busybox_nh" dev="sde20" ino=681 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=file permissive=0
[   14.003177]@0 type=1400 audit(8087831.033:6): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.026279]@0 type=1400 audit(8087831.040:7): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.045680]@0 type=1400 audit(8087831.040:8): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.045912]@0 type=1400 audit(8087831.043:9): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.046074]@0 type=1400 audit(8087831.043:10): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.046180]@0 type=1400 audit(8087831.046:11): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.049948]@0 type=1400 audit(8087831.046:12): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.050112]@0 type=1400 audit(8087831.053:13): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.050231]@0 type=1400 audit(8087831.060:14): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.050319]@0 type=1400 audit(8087831.060:15): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.050428]@0 type=1400 audit(8087831.063:16): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.050723]@0 type=1400 audit(8087831.063:17): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.050844]@0 type=1400 audit(8087831.063:18): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.050935]@0 type=1400 audit(8087831.066:19): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.051037]@0 type=1400 audit(8087831.066:20): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.051131]@0 type=1400 audit(8087831.070:21): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.051435]@0 type=1400 audit(8087831.070:22): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.051716]@0 type=1400 audit(8087831.070:23): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.051851]@0 type=1400 audit(8087831.073:24): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.051929]@0 type=1400 audit(8087831.073:25): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.052010]@0 type=1400 audit(8087831.076:26): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   14.052077]@0 type=1400 audit(8087831.076:27): avc: denied { module_load } for pid=1 comm="init" scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=system permissive=0
[   15.383536]@0 type=1400 audit(1476724586.446:28): avc: denied { setgid } for pid=825 comm="zygote64" capability=6 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app:s0:c512,c768 tclass=capability permissive=0
```
what i've tried
- add a line into init.te according to [this](https://code.google.com/p/android/issues/detail?id=184188)
- adding `module_load` entry into external/sepolicy/access_vectors
- add `setenforce 0` before insmod in 06-load-modules

I've compiled the kernel with permissive support, a kernel flag xxx_DEVELOP maybe, but the kernel start with enforcing mode.

Any suggestions? 🤕

**Comment by jcadduono** [comment]
You can grep $split_img/boot.img-cmdline for 'androidboot.selinux=' and sed replace enforcing with permissive or printf "androidboot.selinux=permissive" >>  to it

**Comment by discipuloosho** [comment]
This can help you.
https://github.com/discipuloosho/android_kernel_moto_shamu/commit/36606d7f60d731dd6901edb9a8c4714fa7f8cdaa

**Comment by ttimasdf** [comment]
After reading selinux codes, I've figured out a way to enable kernel module loading without setting permissive. The missing permission is `fd:use` and `system: module_load` permission for init process. But if I patch it into my kernel, I will have to overwrite the entire sepolicy.. Is it possible for the installer?

**Comment by ttimasdf** [comment]
Oh, maybe SELinux is too annoying for hackers.. That shouldn't be that complicated anyway. I should release a permissive kernel for the majority, avoiding much modification on device config files. Sorry for my ignorance... 😩

**Comment by jcadduono** [comment]
if you get experienced enough with sepolicy modifications, you should learn about this: https://github.com/phhusson/sepolicy-inject
we eventually want to integrate that into our installer and be able to inject policy rules with patch.d scripts, i could do that now but i'm not really knowledgeable in what rules to inject

**Comment by ttimasdf** [comment]
Oh yeah, nearly forget about that. I've looked through it before. But there is a question.  though the sepolicy database version is not a problem as the parser library is compiled with the tool chain, but the library, especially `libsepol.so` is compiled for x86/64 according to host arch. The static linked version in `sepolicy-inject` is the same. However, to include that project inside ours, for the patch process is on the phone, we have to either 
- compile it against amd{,64} and do it on the go,
- or dump the sepolicy file from ramdisk and patch it
- or just generate a new one like me. 

---
Sorry for late reply. My mail client failed to send my email and I didn't realize it.

**Comment by ttimasdf** [comment]
Oh yeah, nearly forget about that. I've looked through it before. But there is a question.  though the sepolicy database version is not a problem as the parser library is compiled with the tool chain, but the library, especially `libsepol.so` is compiled for x86/64 according to host arch. The static linked version in `sepolicy-inject` is the same. However, to include that project inside ours, for the patch process is on the phone, we have to either 
- compile it against amd{,64} and do it on the go,
- or dump the sepolicy file from ramdisk and patch it
- or just generate a new one like me. 

发自 BlueMail




-------- 原始消息--------
来自： James Christopher Adduono <notifications@github.com>
发送： Fri Oct 21 14:58:51 GMT+08:00 2016
收件人： offensive-security/nethunter-devices <nethunter-devices@noreply.github.com>
抄送： Tim Zhang <ttimasdf@gmail.com>, Author <author@noreply.github.com>
主题： Re: [offensive-security/nethunter-devices] [Oneplus3cm] Add kernel for Cyanogenmod (#28)

if you get experienced enough with sepolicy modifications, you should learn about this: https://github.com/phhusson/sepolicy-inject
we eventually want to integrate that into our installer and be able to inject policy rules with patch.d scripts, i could do that now but i'm not really knowledgeable in what rules to inject

**Comment by jcadduono** [comment]
any news on this device / if it's ready for merge with master?

**Pull request closed without merging**
