### PR TITLE
Add Motorola Moto G5 Kernel

### PR DESCRIPTION
**Pull request by rajeshdubey293**
Hi, I would like to show my work, I hope you will like it.
I have made kernel for Motorola Moto G5 that supports all the things that is required for nethunter application. 

https://forum.xda-developers.com/g5/development/kali-nethunter-motorola-moto-g5-cedric-t3807191/post76879558#post76879558

### CODE REVIEW

**Comment by jcadduono** [comment]
Thanks for your contribution, be sure to check out the files changed section, there are some oddities that appear to have been imported from one of the testing branches (Galaxy S8)
You may want to interactive rebase (git rebase -i HEAD~x) and edit the commit that seems to have added them in.

I suggest also copying the `lib/modules` folder from the command when building:
`make INSTALL_MOD_PATH="." INSTALL_MOD_STRIP=1 modules_install`

This will include all the info needed for modprobe to automatically load modules while in Android and the Kali chroot.

**Comment by rajeshdubey293** [comment]
Sure sir. I will do that and after i will commit the changes.

**Comment by rajeshdubey293** [comment]
@jcadduono Everything is set up now.! you can check out.

**Comment by rajeshdubey293** [comment]
@jcadduono Done !..actually I forgot to commit my changes yesterday so it happened..!

**Comment by jcadduono** [comment]
Great! First merge in like half a year lol. You can add /lib/modules to your .gitignore and the installed modules will stop showing up in your git work. (I see that you committed them)

**Comment by rajeshdubey293** [comment]
thank you very much..!!

**Pull request merged**
