### PR TITLE
[NVIDIA Shield Tablet] Nougat support added

### PR DESCRIPTION
**Pull request by SecurityAddicted**
Hello,
I've built a Nougat-compatible kernel for the Shield Tablet, I'm using it since a few days on my tab without issues (LineageOS 14.1 + Nethunter). Based on BitO-K11-005 (https://github.com/BitOBSessiOn/android_kernel_nvidia_shieldtablet) with patches added.
Kernel sources: https://github.com/SecurityAddicted/android_kernel_nvidia_shieldtablet
Let me know if you need any other info to merge the pull request.
Thanks.

### CODE REVIEW

**Comment by elmo315** [comment]
How do I download the kernel?

**Comment by SecurityAddicted** [comment]
While this PR is merged, a test build can be downloaded from:
https://mega.nz/#!A0xVwQwA!QETEOWj-a5p6Wzbf11UaSp51b4fShyazOVqzdvDdujQ

**Comment by Aranadin** [comment]
I'll give this a whirl, thanks for the kernel :)

**Comment by lswordfishl** [comment]
Could anyone help with an installation of this kernel? Im getting error 1 in twrp when trying to install it

**Comment by KNO56** [comment]
> Could anyone help with an installation of this kernel? Im getting error 1 in twrp when trying to install it

Bit late to the party, but I fixed it a while ago by using an older version of TWRP, version 3.1.1-0 to be precise. Hope it works for you!

**Comment by Re4son** [comment]
devices.cfg: ok
kernels.txt: ok
image: ok
modules: ok
tested: no
published: no

**Pull request merged**
