### PR TITLE
[Moto G5] Add LineageOS 14.1 support for cedric

### PR DESCRIPTION
**Pull request by rajeshdubey293**
please have a look on this.

### CODE REVIEW

**Comment by jcadduono** [comment]
the extra devices.cfg section is unnecessary as the previous one will cover it, you can just change the version line to something like...
`version = "1.2 (7.1) & 1.1 (8.0+)"`

**Comment by rajeshdubey293** [comment]
@jcadduono Done.!

**Comment by rajeshdubey293** [comment]
@jcadduono hey ! I have added support for osprey LineageOS 14.1. have a look on this.!

**Comment by rajeshdubey293** [comment]
now also added support LineageOs 15.1 for Moto G 2015

**Comment by Re4son** [comment]
devices.conf: ok
kernels.txt: ok
image: ok
modules: ok
tested: no, public feedback on xda
published: cedric: https://forum.xda-developers.com/g5/development/kali-nethunter-motorola-moto-g5-cedric-t3807191
           osprey: https://forum.xda-developers.com/2015-moto-g/orig-development/kali-nethunter-moto-g-2015osprey-t3815178

**Pull request merged**
