### PR TITLE
Added new device MiPad1

### PR DESCRIPTION
**Pull request by RahulTheVirus**
Hi!
Here a new device name MiPad1 [mocha].
Please merge this into official branch.

Thanks & Regards
RahulTheVirus!

### CODE REVIEW

**Comment by jcadduono** [comment]
looks good to me now, although i am not sure we want to merge this due to kitkat being incredibly out of date and dropping kitkat support altogether seems like a good option soon
for interested users you can leave this PR open
@binkybear what are your thoughts

i think this is a fine device to support but perhaps best to wait for lingeageos support to improve and submit a lineageos based kernel

**Comment by RahulTheVirus** [comment]
Actually device has Tegra K1 so it is good to run nethunter.
.
we don't have either official blobs or bootloader source to upgrade stable android version.
some devs ported shielded blobs but without bootloader source that is not too good.
so our best aproch is KK.☺😊

**Comment by jcadduono** [comment]
bootloader does not need any modifications, its job is only to load kernel and ramdisk into memory and initialize kernel with a command line containing device info and memory pointers to ramdisk location, your device only needs compatibility shims to support newer android versions which with enough effort can be accomplished without needing sources

**Comment by binkybear** [comment]
Kitkat is really old but if kernel version works with Kali then I have no issues merging this.

**Comment by RahulTheVirus** [comment]
will start with android l

**Pull request closed without merging**
