### PR TITLE
Added Galaxy S6/S6 Edge AOSP Kernel Files

### PR DESCRIPTION
**Pull request by madScript01**
Here is my Galaxy S6/S6 Edge Image files but now with a working Drivedroid patch and with almost all functions (Missing HiD compatibility only). Both devices have the "dtb.img" and the "Image" file for both kernels.

This is based off TeamNexus kernel source code for the LineageOS nougat rom.

### CODE REVIEW

**Comment by kimocoder** [comment]
Has wireless injection patch been included? The mac80211 patch which could be found in the wiki?

**Comment by madScript01** [comment]
yes, it has, you can check the net/mac80211/tx.c file

**Comment by madScript01** [comment]
And has all tge monitor mode drivers

**Comment by jcadduono** [comment]
Hi, went over your kernel config, can you please include:
```
CONFIG_FHANDLE=y
CONFIG_EXPORTFS=y
CONFIG_DEFAULT_CUBIC=y
CONFIG_DEFAULT_TCP_CONG="cubic"
CONFIG_DNS_RESOLVER=m
CONFIG_BT_RFCOMM=m
CONFIG_BT_ATH3K=m
CONFIG_CIFS=m (currently y, CIFS is definitely something you want in module form)
CONFIG_CIFS_SMB2=y
```
and I can't remember the exact config names to enable RTL2832 DVB, but you can go to device drivers -> multimedia support -> [*] Media USB adapters [*] Digital TV support -> Media USB adapters -> [*] Support for various USB DVB -> [*] Realtek RTL28xxU DVB USB support

that should do it!

**Comment by madScript01** [comment]
Working on it

**Comment by madScript01** [comment]
Ok, files added, sorry for the second commit, I've confused myself. it's "zeroltexx" and not "zeroflte"

**Comment by madScript01** [comment]
Never mind, just fixed it

**Comment by kimocoder** [comment]
Good job sir

**Comment by madScript01** [comment]
Thanks :)

**Comment by madScript01** [comment]
Added a missing line to devices.cfg

**Comment by jcadduono** [comment]
Looks good to me, does the install succeed and are you able to use `modprobe cifs` and see it in lsmod after that without issue

**Comment by jcadduono** [comment]
that should have been fixed by adding the `arm = arm64` line

**Comment by madScript01** [comment]
Ok, thanks I will try it

**Comment by madScript01** [comment]
OK so firstly after install I've runned the desired command and this was the output ..Output

**Comment by madScript01** [comment]
So then I've navigated to the original root of my phone and then I've discovered that the lib/modules folder was in the lib/modules of my androidsu root so then I've copied the folder to the root of the Kali terminal and I rerwited the command and this was the output ... 2nd output

**Comment by madScript01** [comment]
Is anything wrong or should I do anything else

PS: kalifs are updated and for that reason they have a different md5 hash, when I download kalifs through nethunter app I've a error because md5 hash doesn't match. I've to manually download them from the repo

**Comment by jcadduono** [comment]
if the kernel installed properly using the latest from build.py then it should have installed the modules in /system/lib/modules and /lib/modules should exist in the boot image/ramdisk and be a symlink to /system/lib/modules

does /lib/modules/3.10.107....... exist in androidsu? you should be able to modprobe from androidsu without making any changes

i think i should actually bind mount inside bootkali to fix the issue you ran into

https://github.com/offensive-security/nethunter-app/blob/master/assets/scripts/bootkali_init#L149
after that line should actually be
`$busybox mount -r -o bind /system/lib/modules $mnt/lib/modules`

**Comment by jcadduono** [comment]
i'm also a little confused about your kernel sources, are you using my build.sh script, is it working for you? if so that's great, they work better when you set in your config
```
CONFIG_LOCALVERSION="-"
# CONFIG_LOCALVERSION_AUTO is not set
```
then set https://github.com/madScript01/TeamNexusNethunter/blob/los-14.1/build.sh#L80
to
`export LOCALVERSION=madScript01-$TARGET-$DEVICE-$VARIANT-$VER` (if you wanted your name in the version tag)

**Comment by madScript01** [comment]
I only used the gendtb.sh script, I was a little bit confused with your  build script so I justchecked what where the gendtb.sh dependencies on your build.sh script and I just added them, but I can go right away change some things

**Comment by jcadduono** [comment]
It exists after adding CONFIG_FHANDLE=y

**Comment by madScript01** [comment]
So, I should add that line after the CONFIG_FHANDLE=y right?

**Comment by madScript01** [comment]
Ok, so I've discovered that in official nougat rom, the s6 has a smaller kernel Image, and it has enough space for all the drivers and patches, should I merge kali nethunter for aosp (less stable) or should I make a new project for official firmware (more stable)

**Comment by jcadduono** [comment]
I don't know what to say about it just enable it

**Comment by madScript01** [comment]
Ok, done now I'm going to rebuild the kernel Image and the Kernel modules so we can proceed with the merge

**Comment by madScript01** [comment]
Ok, everything done and I've also found a Synapse patch which included HiD support that I've commited into a ramdisk patch everything is now ready to merge I think

**Comment by kimocoder** [comment]
@bozwald take a look at the work been done here, adding HID support in kernel etc.. might be some useful knowledge for our project

**Comment by bozwald** [comment]
@kimocoder thanks for this,


Great work guys really amazing.

**Comment by madScript01** [comment]
Just added some missing HiD files

**Comment by madScript01** [comment]
I think now its ready to merge

**Comment by jcadduono** [comment]
is there a reason you filled the ramdisk folder with....everything
it is only for files that need to be added to the ramdisk, not replaced or edited
if you need to edit specific files in the ramdisk i suggest using sed in a patch.d script

**Comment by madScript01** [comment]
I only filled them to try to make HiD to work, and now it works, but only with synapse

**Comment by madScript01** [comment]
I also managed to make nethunter compatible with stock nougat firmware with everything working. In the galaxy s6 the only that I found to make HiD working was with Synapse, so I think that should be included inside the ramdisk folder

**Comment by madScript01** [comment]
It's not filled with everything its just filled with some files, I did just like the oneplus 5 version with the ramdisk addingof some files

**Comment by madScript01** [comment]
I've done many changes and I'm about to make another pull request because this one is getting to old and outdated

**Pull request closed without merging**
