### PR TITLE
Add LineageOS 15.1 support for OnePlus3T

### PR DESCRIPTION
**Pull request by flypatriot**
LineageOS 15.1 Boeffla Kernel with full NetHunter features support.
[Thread on XDA](https://forum.xda-developers.com/oneplus-3t/development/nethunter-arm64-rom-oneplus-3t-t3918421).

### CODE REVIEW

**Comment by Re4son** [comment]
Great job, thanks for your contribution. Does the kernel have the HID gadget patch and CD-RO patch applied?

**Comment by flypatriot** [comment]
HID patch applied. CD-ROM work's by default but only with drivedroid v.0.10.38.

**Comment by flypatriot** [comment]
I'll add some changes soon to fix 'bluetooth don't power on' issue.

**Comment by yesimxev** [comment]
@flypatriot Maybe unrelated to your bluetooth issue, but on my S6 edge Lineage14.1, rfkill soft blocked the bluetooth on boot. So I added the kali boot script 
`rfkill unblock bluetooth`
and android could turn on/off bluetooth after

**Comment by flypatriot** [comment]
@yesimxev Thank's for your reply. But it's my own fault. I've forgotten to switch MSM_BT_POWER.

**Comment by Re4son** [comment]
Great stuff. Happy for me to merge?

**Pull request merged**
