### PR TITLE
[Lenovo K8 Note]support for Oreo

### PR DESCRIPTION
**Pull request by byomdwi**
XDA Thread - https://forum.xda-developers.com/k8-note/development/manning-densetsu-kernel-t3885906

### CODE REVIEW

**Comment by Re4son** [comment]
Awesome, thanks.
Is that a stock kernel or have you customised it?
The repo sounds very official. Would you be able to add the 80211 injection patch and HID patches?

**Comment by byomdwi** [comment]
Yes, its a stock kernel that i had customised..
The 802.11 injection patch is already added..

Still working on getting HID up and running.

**Comment by byomdwi** [comment]
Ok, then  i'll add HID patches first...

**Comment by byomdwi** [comment]
I have lost the device...
So wont be working on it anymore.

**Pull request closed without merging**
