### PR TITLE
Add Nougat support OnePlus 2 CM

### PR DESCRIPTION
**Pull request by brandonindar**

### CODE REVIEW

**Comment by jcadduono** [comment]
need to add source links to kernels.txt and modify devices.cfg still, you can see duplicate maintainers per device examples in devices.cfg for reference

**Comment by cyrus104** [comment]
Sorry to create an issue for this when it was already being worked. I would like to check the status of this and if there is any way I can help test.

**Comment by brandonindar** [comment]
Here is the [kernel source.](https://github.com/brandonindar/android_kernel_oneplus_msm8994)
I have started a thread [here. ](http://forum.xda-developers.com/oneplus-2/development/nethunter-3-15-3-oneplus-2-cm-14-nougat-t3507548)

**Comment by Re4son** [comment]
Would be great if you could add the corresponding entries to "kernel.txt" and "devices.cfg" as @jcadduono  asked for. Many thanks.

**Comment by Re4son** [comment]
Closed due to inactivity.
Please re-open with the missing information if required.

**Pull request closed without merging**
