### PR TITLE
[Moto X2] LinageOS Kernel

### PR DESCRIPTION
**Pull request by xchwarze**
For Motorola X2 (2014)

### CODE REVIEW

**Comment by kimocoder** [comment]
@xchwarze have mac80211 injection patch or HID patches been applied to this kernel?

**Comment by jcadduono** [comment]
@kimocoder thats why we have sources in kernels.txt, and it appears he has applied mac80211 https://github.com/xchwarze/nethunter-motorola-x2-kernel/commits/cm-14.1

don't see HID patches though

**Comment by xchwarze** [comment]
hello! 
I'm compiling right now with HID keyboard/mouse gadget patch

**Comment by kimocoder** [comment]
Awesome. Great work adding support for another device.

**Comment by xchwarze** [comment]
there the patch is already commited!

to flash it modify the script "Kali NetHunter boot image patcher script" (boot-patcher.sh)
old:
`5d00) rdformat=lzma; decompress="lzma -dc" ;;`

new:
`5d0|5d00) rdformat=lzma; decompress="lzma -dc" ;;`

https://forums.kali.org/showthread.php?37981-Problems-flashing-new-Moto-X2-custom-kernel-Unknown-ramdisk-compression-format-(5d0

**Comment by jcadduono** [comment]
@xchwarze thanks for find, fixing the hexdump command (should be %.2x not %x)

**Comment by Re4son** [comment]
@jcadduono @kimocoder happy for me to merge?

**Pull request merged**
