### PR TITLE
Added new device mocha

### PR DESCRIPTION
**Pull request by RahulTheVirus**

### CODE REVIEW

**Comment by Re4son** [comment]
Nice job.
Do you have working nethunter images using these kernels published somewhere?

**Comment by RahulTheVirus** [comment]
Maybe I don't remember.
but i have tested it & it's working properly with keyboard .
and form our Telegram group user's tested with several adopters.

Right now i can't share screenshot because i have totally changed partition table of my device
an installed KALI netively desktop version using L4T project of NVIDIA.

**Comment by Re4son** [comment]
devices.cfg: ok
kernels.txt: ok
image: ok
modules: ok
tested: no
published: ?

**Comment by RahulTheVirus** [comment]
it's tested and working without any issue with generic version of nethunter installer.

**Pull request merged**
