### PR TITLE
Added new device MiPad1 [mocha]

### PR DESCRIPTION
**Pull request by RahulTheVirus**
Hi!
I have added new device in awsome nethunter device.
With working HID keyboard & mouse.
Please merge this into official branch.

Thanks & Regards
RahulTheVirus!

### CODE REVIEW

**Comment by jcadduono** [comment]
i'm not sure about merging kitkat devices, afaict your device has nougat support via lineageos going by xda threads, have you tried that?
also consider fixing up your kernel commits, you should have a commit for every specific change to reduce confusion

**Comment by RahulTheVirus** [comment]
yes we have M & N but they are not as stable as they can run nethunter.
They have some issue wich varry with device.
So for us best aproch is run net hunter with official MIUI rom.
Until Los become stable .

**Comment by jcadduono** [comment]
Also some issues in devices.cfg

Version should be version
device name should be devicenames
arch line unnecessary default is arm
block line only needed if it fails to flash due to unable to find boot partition

**Comment by RahulTheVirus** [comment]
Fixed 
Thanks!

**Comment by jcadduono** [comment]
devicenames

**Comment by RahulTheVirus** [comment]
Ok i'll make a clean branch and create pull request again ..
Thanks !

**Comment by jcadduono** [comment]
there is no need you can just use git rebase -i

**Pull request closed without merging**
