### PR TITLE
[hammerheadcafcm] Update kernel

### PR DESCRIPTION
**Pull request by chrisk44**
Update kernel for hammerheadcafcm (sync with LineageOS).

Btw, I did a git rebase, now it says it can't be automatically merged. If there's a problem, I'll start over.

### CODE REVIEW

**Comment by jcadduono** [comment]
just use git rebase and git rebase --skip until you reach your newest commit

**Comment by chrisk44** [comment]
i did it... if you can merge it, go ahead...

**Comment by jcadduono** [comment]
you need to force push it it doesnt look like you updated it

**Comment by jcadduono** [comment]
you can also do this:
```
git reset --hard f3b8470d94
git cherry-pick -n eef193b
git cherry-pick -n e097110
git commit
<enter your new commit message for updating device>
```

**Comment by chrisk44** [comment]
It says everything up-to-date. It was uploading for an eternity with my connection, it pushed. The version is correctly updated. If I do that, will it revert to the state it was when I forked it? because I'm now updating only one kernel, but I have 2 more that I have uploaded.

**Comment by jcadduono** [comment]
ok i think the issue is that you dont have us as a remote...
```
git remote add ofsc https://chrisk44@github.com/offensive-security/nethunter-devices.git
git fetch ofsc
git rebase ofsc/master
```

**Comment by chrisk44** [comment]
I do, it's upstream. That's how I sync with you.

**Comment by jcadduono** [comment]
hmm well according to your git history you are still on top of november commit

**Comment by chrisk44** [comment]
`git rebase upstream/master`
First, rewinding head to replay your work on top of it...
Applying: Update Nexus 5 caf kernel and fix hammerheadcafcm directory
Using index info to reconstruct a base tree...
A	nougat/hammerheadcaf/zImage-dtb
Falling back to patching base and 3-way merge...
CONFLICT (rename/rename): Rename "nougat/hammerheadcaf/zImage-dtb"->"nougat/hammerheadcafcm/zImage-dtb" in branch "f3b8470d94dc637783ddef8f408605c682517286" rename "nougat/hammerheadcaf/zImage-dtb"->"nougat/hammerheadcafcm/zImage-dtb-merged" in "Update Nexus 5 caf kernel and fix hammerheadcafcm directory"

`git rebase --skip` did the same.

**Comment by jcadduono** [comment]
look up a guide on how to fix conflicts and rebase?

**Comment by chrisk44** [comment]
ok finally it can be merged

**Comment by jcadduono** [comment]
...i would just start over

**Pull request closed without merging**
