### PR TITLE
[NOT READY] [Honor 5x] Add kernel to stable and add missing configs to kernel

### PR DESCRIPTION
**Pull request by DeadSquirrel01**
The dead squirrel is retourned!!!
In this update I've added honor 5x kernel to master branch and I've included wifi module due to non working wifi in the previous build

### CODE REVIEW

**Comment by jcadduono** [comment]
wlan.ko belongs in modules folder for it to work

**Comment by DeadSquirrel01** [comment]
Heyy, I added the configs you told me to add. Regarding wifi module, some users reported that wifi is working, so, it is not needed anymore

**Comment by jcadduono** [comment]
did u want to rebrand this to lineageOS before i merge

**Comment by DeadSquirrel01** [comment]
Now I've rebranded and also changed version 1.1 which I forgot to do, but I left the branch name "cm-13.0" because I've seen in many cm repos that "cm-" branches are still used. Anyway tell me if you want I change it

**Pull request merged**
