### PR TITLE
[Oneplus2] Oreo support for AOSP based roms

### PR DESCRIPTION
**Pull request by xNNism**
- ##### Kernel works with AOSP based roms like AOSP-Extended or AOSIP
i've tested it with [lineage-15.1-20180724-nightly-oneplus2-signed.zip](https://mirrorbits.lineageos.org/full/oneplus2/20180724/lineage-15.1-20180724-nightly-oneplus2-signed.zip) and it worked too, but i did not tested it as much as the AOSP branch.  Anyways a LineageOS build is in the pipeline.

###### Note : The [official Magisk release](https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445) was used to gain superuser access.

---

- ##### Tested and working: 

 ###### Note: I tested everything using a cheap USB Type-C Adapter

- HID support (seems fully functional)
- Packet injection (tested with ath9k_htc based [TP-Link TL-WN722N v2](https://www.tp-link.com/us/products/details/cat-5520_TL-WN722N.html))
- Ethernet over USB (I've tested [RTL8153](https://www.amazon.com/USB-Hub-Badalink-Ethernet-Connector/dp/B01J1N9OD0) and [DM9601](https://projectgus.com/2013/03/anatomy-of-a-cheap-usb-ethernet-adapter/))
- Y-cable Charging (I've tested a [Acasis 3Port Hub](https://www.aliexpress.com/item/10070TW-Acasis-H027-Mobile-Tablet-PC-Charging-Cable-OTG-Micro-USB-HUB-3Ports-Simultaneous-Charging-Power/32340638202.html) and a unbranded [OTG-Hub](https://www.ebay.com/p/4-in-1-Micro-USB-Hub-OTG-Charging-Cable-Extension-Adapter-Android-Samsung-Tablet/1082097250?iid=202068683548)

---
- ##### The Kernel configuration file can be viewed here:
[xNNism/aosp_nethunter-kernel_oneplus_msm8994/arch/arm64/configs/nethunter_defconfig](https://github.com/xNNism/aosp_nethunter-kernel_oneplus_msm8994/blob/nethunter-8.1/arch/arm64/configs/nethunter_defconfig)

---

- ##### Patches i've applied: 
1. mac80211.compat08082009.wl_frag+ack_v1.patch [Link to patch](https://github.com/xNNism/aosp_nethunter-kernel_oneplus_msm8994/commit/517706ad0a138bfa19f603ad5e93a177184870a9)
2. drivers/bluetooth/btusb.c: patch for build errors / disable FW download [Link to patch](https://github.com/xNNism/aosp_nethunter-kernel_oneplus_msm8994/commit/be450d25005e3394e5dcd4bac425009da1aa9a92)

---
- #### Kernelsource:
 [https://github.com/xNNism/aosp_nethunter-kernel_oneplus_msm8994](https://github.com/xNNism/aosp_nethunter-kernel_oneplus_msm8994)

### CODE REVIEW

**Comment by darksty** [comment]
hi will you make some oneplus 3T oreo kernel?

**Comment by darksty** [comment]
And is good if support for official OxygenOS 5.0.x




------------------ 原始邮件 ------------------
发件人: "xNN"<notifications@github.com>;
发送时间: 2018年7月30日(星期一) 晚上11:27
收件人: "offensive-security/nethunter-devices"<nethunter-devices@noreply.github.com>;
抄送: "Jackass."<625688543@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [offensive-security/nethunter-devices] [Oneplus2] Oreo supportfor AOSP based roms (#149)




I could certainly try but without owning a Oneplus  3T i will not be able to test the functionality at all...
 If time allows i'll compile a build and send it to you. But remember that it will be untested an you'll be the first...!

**Comment by Re4son** [comment]
Late to the party but do you have updates to the devices.conf and kernels.txt for this commit? Have you published your image somewhere?

**Comment by kimocoder** [comment]
https://github.com/xNNism/aosp_nethunter-kernel_oneplus_msm8994

:1st_place_medal:

**Comment by Re4son** [comment]
Thanks kimocoder. Do you know if there's a nethunter image published with that kernel? Anywhere on xda for example?

**Comment by Re4son** [comment]
Closed due to inactivity.
Please re-open with the missing information if required.

**Pull request closed without merging**
